In [25]:
import numpy as numpy
import pandas as pd
from ydata_profiling import ProfileReport
from sklearn.impute import SimpleImputer
from sklearn.impute import KNNImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from scipy import stats
from scipy.stats.mstats import winsorize
from sklearn.preprocessing import (
    LabelEncoder,
    OrdinalEncoder,
    OneHotEncoder,
    Binarizer
)

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler, Normalizer, MinMaxScaler, MaxAbsScaler, RobustScaler

---

# 📘 Part A: Conceptual Foundation

---

# 📊 1. What is Data Analysis?

## 📖 Definition

Data Analysis is the process of collecting, cleaning, organizing, exploring, and interpreting data to discover useful information and support better decision-making.

For this project, data analysis helps understand customer financial behavior and predict whether a customer may default on a loan.

---

## 🎯 Objectives of Data Analysis

- 📥 Collect meaningful data
- 🧹 Clean the dataset
- 📈 Discover patterns and trends
- 🔍 Identify relationships between variables
- 🤖 Prepare data for Machine Learning
- 📊 Support better business decisions

---

## 🔄 Steps of Data Analysis

### 1️⃣ Data Collection
Collect customer information from different sources.

### 2️⃣ Data Cleaning
Handle missing values, duplicates, incorrect values, and outliers.

### 3️⃣ Data Exploration
Use statistics and visualizations to understand the data.

### 4️⃣ Data Transformation
Convert data into a suitable format using encoding and scaling.

### 5️⃣ Model Building
Train a Machine Learning model using the processed dataset.

### 6️⃣ Result Evaluation
Evaluate the model using different performance metrics.

---

## 💡 Interpretation

> ✅ In this Credit Risk Dataset, data analysis helps us understand customer behavior by analyzing features such as **annual income, loan amount, credit score, repayment history, and spending ratio**. Proper analysis improves prediction accuracy and helps banks make better loan approval decisions.

---


# 🚀 2. How to Plan a Data Science Project

## 📖 Defination

A Data Science project follows a structured process to solve real-world business problems using data.

---

## 🛠 Step 1: Business Understanding

Understand the problem before working with the data.

### Example

Predict whether a customer will default on a loan.

### 💡 Interpretation

> 🏦 Understanding the business problem helps us select the right data and Machine Learning approach.

---

## 📥 Step 2: Data Collection

Collect customer information such as:

- Age
- Income
- Credit Score
- Loan Amount
- Employment Type
- Transaction Count
- Repayment History

### 💡 Interpretation

> 📊 High-quality data leads to more accurate predictions.

---

## 🧹 Step 3: Data Cleaning

Perform:

- Missing Value Imputation
- Duplicate Removal
- Outlier Detection
- Data Type Correction

### 💡 Interpretation

> ✨ Clean data improves the reliability and performance of Machine Learning models.

---

## 📈 Step 4: Exploratory Data Analysis (EDA)

Analyze data using:

- Mean
- Median
- Standard Deviation
- Histogram
- Boxplot
- Correlation Matrix

### 💡 Interpretation

> 🔍 EDA helps discover patterns, relationships, and unusual values before modeling.

---

## ⚙ Step 5: Data Preprocessing

Apply:

- Encoding
- Scaling
- Feature Engineering
- Feature Selection

### 💡 Interpretation

> 🤖 Machine Learning algorithms require properly prepared numerical data.

---

## 🤖 Step 6: Model Building

Train a Machine Learning algorithm.

Examples:

- Logistic Regression
- Decision Tree
- Random Forest

### 💡 Interpretation

> 📈 The model learns customer behavior and predicts loan default risk.

---

## 📊 Step 7: Model Evaluation

Evaluate the model using:

- Accuracy
- Precision
- Recall
- F1 Score

### 💡 Interpretation

> 🎯 Evaluation measures how accurately the model predicts customer defaults.

# 🧠 3. How to Frame a Machine Learning Problem

## 📖 Defination

Framing a Machine Learning problem means identifying the target variable, selecting features, preparing the data, and choosing an appropriate learning algorithm.

---

## 🎯 Step 1: Define Target Variable

Target Variable:

```text
default_flag
```

- 0 → No Default
- 1 → Default

### 💡 Interpretation

> ✅ This project is a **Binary Classification** problem because the output has only two possible classes.

---

## 📊 Step 2: Select Features

Input Features:

- age
- annual_income
- loan_amount
- credit_score
- repayment_history
- transaction_count
- spending_ratio
- region
- education_level
- employment_type
- loan_purpose

### 💡 Interpretation

> 📈 These customer attributes help predict whether a customer will repay the loan.

---

## 🧹 Step 3: Data Preprocessing

Apply:

- Missing Value Imputation
- Outlier Treatment
- Encoding
- Scaling
- Feature Engineering

### 💡 Interpretation

> ⚡ Proper preprocessing improves model performance and prediction accuracy.

---

## 🤖 Step 4: Train the Model

Train the Machine Learning algorithm using processed data.

### 💡 Interpretation

> 📚 The model learns hidden patterns from customer information.

---

## 📊 Step 5: Test the Model

Evaluate the model using unseen test data.

### 💡 Interpretation

> 🔍 Testing checks whether the model can accurately predict loan defaults for new customers.

---

# 2 . Explain Tensors with NumPy Examples

## 📖 Defination

A Tensor is a multidimensional array used to store numerical data. Tensors are the basic building blocks of Machine Learning and Deep Learning.

---

## 📌 Types of Tensors

| Tensor Type | Dimension | Example |
|-------------|-----------|----------|
| Scalar | 0D | Single Value |
| Vector | 1D | List of Numbers |
| Matrix | 2D | Rows and Columns |
| Tensor | 3D+ | Multiple Matrices |

---

## 🟢 Scalar (0D Tensor)

```python
import numpy as np

scalar = np.array(10)

print(scalar)
print(scalar.ndim)
```

### 💡 Interpretation

> 🔹 A scalar stores only one numerical value.

---

## 🟡 Vector (1D Tensor)

```python
vector = np.array([10,20,30,40])

print(vector)
print(vector.ndim)
```

### 💡 Interpretation

> 📈 A vector stores values in a single dimension, such as customer ages.

---

## 🔵 Matrix (2D Tensor)

```python
matrix = np.array([
    [25,500000],
    [40,700000],
    [35,650000]
])

print(matrix)
print(matrix.ndim)
```

### 💡 Interpretation

> 📊 A matrix stores data in rows and columns. In this project, each row represents a customer and each column represents a feature.

---

## 🟣 3D Tensor

```python
tensor3d = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

print(tensor3d.ndim)
```

### 💡 Interpretation

> 🚀 A 3D tensor stores multiple matrices together and is commonly used in Deep Learning applications.

---

## 📐 Tensor Shape

```python
print(matrix.shape)
```

### 💡 Interpretation

> 📏 Shape tells us the number of rows and columns in the tensor.

---

## 🔢 Tensor Size

```python
print(matrix.size)
```

### 💡 Interpretation

> 📦 Size represents the total number of elements stored inside the tensor.

---

## 🧾 Tensor Data Type

```python
print(matrix.dtype)
```

### 💡 Interpretation

> 🔍 The data type indicates what kind of values are stored (integer, float, etc.).

---

---

# 📘 PART B - Data Acquisition

---

## 📄 Task 1: Load CSV File (Main File)

In [26]:
import pandas as pd

In [27]:
df = pd.read_csv("../Dataset/Customer_Credit_Risk_Dataset.csv")

df.head()

,customer_id,age,gender,region,education_level,employment_type,annual_income,loan_amount,loan_purpose,credit_score,repayment_history,transaction_count,spending_ratio,join_date,default_flag
0,CUST00001,54,Male,South,Graduate,Salaried,886382.09,338184.20,Business,775.9,12,248,28.74,2023-09-09,0
1,CUST00002,32,Male,East,Graduate,Self-Employed,2538050.29,274380.78,Business,484.9,7,439,62.15,2020-11-11,1
2,CUST00003,25,Female,East,Graduate,Self-Employed,2550668.63,1631792.71,Education,316.0,5,63,6.80,2019-02-21,1
3,CUST00004,45,Male,South,Graduate,Self-Employed,1286415.40,213936.12,Car,799.2,17,393,5.06,2023-08-08,0
4,CUST00005,51,Male,South,Graduate,Self-Employed,997939.39,78230.40,Car,513.5,5,370,34.34,2018-09-13,1

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        5000 non-null   object
 1   age                5000 non-null   int64
 2   gender             5000 non-null   object
 3   region             5000 non-null   object
 4   education_level    5000 non-null   object
 5   employment_type    5000 non-null   object
 6   annual_income      5000 non-null   float64
 7   loan_amount        5000 non-null   float64
 8   loan_purpose       5000 non-null   object
 9   credit_score       5000 non-null   float64
 10  repayment_history  5000 non-null   int64
 11  transaction_count  5000 non-null   int64
 12  spending_ratio     5000 non-null   float64
 13  join_date          5000 non-null   object
 14  default_flag       5000 non-null   int64
dtypes: float64(4), int64(4), object(7)
memory usage: 586.1+ KB

In [29]:
df.shape

(5000, 15)

### 💡 Interpretation

✅ The CSV file is successfully loaded into the DataFrame. It contains customer information such as age, annual income, loan amount, credit score, repayment history, and default status. This dataset will be used throughout the project

## 📄 Task 2: Parse JSON File (Customer Metadata)

In [30]:
metadata = pd.read_json("../Dataset/customer_metadata.json")

metadata.head()

  customer_id marital_status  dependents owns_house
0   CUST00001        Married           2        Yes
1   CUST00002         Single           0         No

In [31]:
df = df.merge(metadata, on="customer_id", how="left")

df.head()

,customer_id,age,gender,region,education_level,employment_type,annual_income,loan_amount,loan_purpose,credit_score,repayment_history,transaction_count,spending_ratio,join_date,default_flag,marital_status,dependents,owns_house
0,CUST00001,54,Male,South,Graduate,Salaried,886382.09,338184.20,Business,775.9,12,248,28.74,2023-09-09,0,Married,2.0,Yes
1,CUST00002,32,Male,East,Graduate,Self-Employed,2538050.29,274380.78,Business,484.9,7,439,62.15,2020-11-11,1,Single,0.0,No
2,CUST00003,25,Female,East,Graduate,Self-Employed,2550668.63,1631792.71,Education,316.0,5,63,6.80,2019-02-21,1,NaN,NaN,NaN
3,CUST00004,45,Male,South,Graduate,Self-Employed,1286415.40,213936.12,Car,799.2,17,393,5.06,2023-08-08,0,NaN,NaN,NaN
4,CUST00005,51,Male,South,Graduate,Self-Employed,997939.39,78230.40,Car,513.5,5,370,34.34,2018-09-13,1,NaN,NaN,NaN

### 💡 Interpretation

✅ The customer metadata is successfully imported from the JSON file and merged with the main dataset using the customer_id column. This provides additional customer information for analysis.

## 📄 Task 3: Fetch Records from SQL Database

In [32]:
import pandas as pd
import sqlite3

# Load CSV
df = pd.read_csv("../Dataset/Customer_Credit_Risk_Dataset.csv")   # apna correct CSV name

# Create new SQLite database
conn = sqlite3.connect("loan_database.db")

# Store dataframe into SQL table
df.to_sql("customer_credit", conn, if_exists="replace", index=False)

# Read from SQL
df_sql = pd.read_sql("SELECT * FROM customer_credit", conn)

conn.close()

df_sql.head()

,customer_id,age,gender,region,education_level,employment_type,annual_income,loan_amount,loan_purpose,credit_score,repayment_history,transaction_count,spending_ratio,join_date,default_flag
0,CUST00001,54,Male,South,Graduate,Salaried,886382.09,338184.20,Business,775.9,12,248,28.74,2023-09-09,0
1,CUST00002,32,Male,East,Graduate,Self-Employed,2538050.29,274380.78,Business,484.9,7,439,62.15,2020-11-11,1
2,CUST00003,25,Female,East,Graduate,Self-Employed,2550668.63,1631792.71,Education,316.0,5,63,6.80,2019-02-21,1
3,CUST00004,45,Male,South,Graduate,Self-Employed,1286415.40,213936.12,Car,799.2,17,393,5.06,2023-08-08,0
4,CUST00005,51,Male,South,Graduate,Self-Employed,997939.39,78230.40,Car,513.5,5,370,34.34,2018-09-13,1

### 💡 Interpretation

✅ The repayment history is successfully fetched from the SQL database and merged with the main dataset. This helps analyze customers' previous loan repayment behavior.

## 📄 Task 4: Fetch Data from Dummy API

In [33]:
import requests
import pandas as pd

url = "https://jsonplaceholder.typicode.com/users"

response = requests.get(url)

api_data = response.json()

api_df = pd.DataFrame(api_data)

api_df.head()

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."

### 💡 Interpretation

✅ The data is successfully fetched from the dummy API using the Requests library. The JSON response is converted into a Pandas DataFrame. In real-world banking projects, APIs can provide external information such as interest rates, inflation rates, or economic indicators.

---

# 📊 Part C: Data Understanding & Cleaning

---

### 4. Explore the Dataset using Pandas

In [34]:
df.info

<bound method DataFrame.info of      customer_id  age  gender region education_level employment_type  \
0      CUST00001   54    Male  South        Graduate        Salaried
1      CUST00002   32    Male   East        Graduate   Self-Employed
2      CUST00003   25  Female   East        Graduate   Self-Employed
3      CUST00004   45    Male  South        Graduate   Self-Employed
4      CUST00005   51    Male  South        Graduate   Self-Employed
...          ...  ...     ...    ...             ...             ...
4995   CUST04996   53   Other   East         Primary        Salaried
4996   CUST04997   33  Female   West   Post-Graduate      Unemployed
4997   CUST04998   45   Other  North         Primary        Salaried
4998   CUST04999   43  Female  South         Primary      Unemployed
4999   CUST05000   59   Other  North   Post-Graduate        Salaried

      annual_income  loan_amount loan_purpose  credit_score  \
0         886382.09    338184.20     Business         775.9
1        2538050.29    274380.78     Business         484.9
2        2550668.63   1631792.71    Education         316.0
3        1286415.40    213936.12          Car         799.2
4         997939.39     78230.40          Car         513.5
...             ...          ...          ...           ...
4995     2724324.63    622050.50        Other         795.9
4996     2426825.86    513054.21        Other         778.4
4997     1354811.58   1028097.84        Other         426.5
4998     2670539.94    769693.77        Other         841.0
4999     2941024.87    627409.38    Education         530.3

      repayment_history  transaction_count  spending_ratio   join_date  \
0                    12                248           28.74  2023-09-09
1                     7                439           62.15  2020-11-11
2                     5                 63            6.80  2019-02-21
3                    17                393            5.06  2023-08-08
4                     5                370           34.34  2018-09-13
...                 ...                ...             ...         ...
4995                  4                396           57.59  2023-03-06
4996                 13                182           64.08  2024-01-14
4997                 16                410           45.97  2025-09-25
4998                  4                317           48.00  2020-05-14
4999                  9                388          112.00  2019-02-16

      default_flag
0                0
1                1
2                1
3                0
4                1
...            ...
4995             1
4996             0
4997             1
4998             1
4999             1

[5000 rows x 15 columns]>

### 💡 Interpretation
✅ df.info() displays the dataset structure, data types, and missing values. It helps us understand the data before preprocessing.

In [35]:
df.describe

<bound method NDFrame.describe of      customer_id  age  gender region education_level employment_type  \
0      CUST00001   54    Male  South        Graduate        Salaried
1      CUST00002   32    Male   East        Graduate   Self-Employed
2      CUST00003   25  Female   East        Graduate   Self-Employed
3      CUST00004   45    Male  South        Graduate   Self-Employed
4      CUST00005   51    Male  South        Graduate   Self-Employed
...          ...  ...     ...    ...             ...             ...
4995   CUST04996   53   Other   East         Primary        Salaried
4996   CUST04997   33  Female   West   Post-Graduate      Unemployed
4997   CUST04998   45   Other  North         Primary        Salaried
4998   CUST04999   43  Female  South         Primary      Unemployed
4999   CUST05000   59   Other  North   Post-Graduate        Salaried

      annual_income  loan_amount loan_purpose  credit_score  \
0         886382.09    338184.20     Business         775.9
1        2538050.29    274380.78     Business         484.9
2        2550668.63   1631792.71    Education         316.0
3        1286415.40    213936.12          Car         799.2
4         997939.39     78230.40          Car         513.5
...             ...          ...          ...           ...
4995     2724324.63    622050.50        Other         795.9
4996     2426825.86    513054.21        Other         778.4
4997     1354811.58   1028097.84        Other         426.5
4998     2670539.94    769693.77        Other         841.0
4999     2941024.87    627409.38    Education         530.3

      repayment_history  transaction_count  spending_ratio   join_date  \
0                    12                248           28.74  2023-09-09
1                     7                439           62.15  2020-11-11
2                     5                 63            6.80  2019-02-21
3                    17                393            5.06  2023-08-08
4                     5                370           34.34  2018-09-13
...                 ...                ...             ...         ...
4995                  4                396           57.59  2023-03-06
4996                 13                182           64.08  2024-01-14
4997                 16                410           45.97  2025-09-25
4998                  4                317           48.00  2020-05-14
4999                  9                388          112.00  2019-02-16

      default_flag
0                0
1                1
2                1
3                0
4                1
...            ...
4995             1
4996             0
4997             1
4998             1
4999             1

[5000 rows x 15 columns]>

### 💡 Interpretation
✅ df.describe() provides the statistical summary of numerical columns, such as count, mean, standard deviation, minimum, maximum, and quartile values. It helps us understand the data distribution.

### 5.Pandas Profiling

In [36]:
profile = ProfileReport(
    df,
    title="Customer Credit Risk Dataset Report",
    explorative=True
)

profile.to_file("Customer_Credit_Risk_Profile.html")

profile

print("Profiling Report Generated Successfully!")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 15/15 [00:00<00:00, 36.86it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

Profiling Report Generated Successfully!

### 💡 Interpretation

✅ Pandas Profiling generates a complete summary of the dataset, including data types, missing values, duplicate records, summary statistics, correlations, and feature distributions. It helps us quickly understand the dataset before data preprocessing.

---

## 6.1 Simple Imputer (Numerical - Mean)

In [37]:
mean_imputer = SimpleImputer(strategy="mean")

df["age"] = mean_imputer.fit_transform(df[["age"]])

### 💡 Interpretation

✅ Missing values in the age column were replaced with the mean value of the column.

## 6.2 Simple Imputer (Numerical - Median)

In [38]:
median_imputer = SimpleImputer(strategy="median")

df["credit_score"] = median_imputer.fit_transform(df[["credit_score"]])

### 💡 Interpretation

✅ Missing values in the credit_score column were replaced with the median value, which is suitable for data with outliers.

## 6.3 Simple Imputer (Categorical - Most Frequent)

In [39]:
cat_imputer = SimpleImputer(strategy="most_frequent")

df["employment_type"] = cat_imputer.fit_transform(df[["employment_type"]]).ravel()

### 💡 Interpretation

✅ Missing values in employment_type were filled with the most frequent category.

## 6.4 Most Frequent Category Imputation

In [40]:
df["gender"] = df["gender"].fillna(df["gender"].mode()[0])

### 💡 Interpretation

✅ A missing indicator column was created, and missing values in annual_income were replaced using random samples from existing values.

## 6.6 KNN Imputer

In [41]:
knn = KNNImputer(n_neighbors=5)

df[["annual_income","loan_amount","credit_score"]] = knn.fit_transform(
    df[["annual_income","loan_amount","credit_score"]]
)

### 💡 Interpretation

✅ KNN Imputer filled missing values using the nearest similar records.

## 6.7 MICE Algorithm

In [42]:
mice = IterativeImputer(random_state=42)

df[["annual_income","loan_amount","credit_score"]] = mice.fit_transform(
    df[["annual_income","loan_amount","credit_score"]]
)

### 💡 Interpretation

✅ MICE estimated missing values by learning relationships between multiple features.

## 6.8 Complete Case Analysis

In [43]:
df_complete = df.dropna()

print("Original Shape :", df.shape)
print("After Complete Case Analysis :", df_complete.shape)

Original Shape : (5000, 15)
After Complete Case Analysis : (5000, 15)

### 💡 Interpretation

✅ Rows containing missing values were removed to create a complete dataset.

# 📌 Final Missing Values Check

In [44]:
df.isnull().sum()

customer_id          0
age                  0
gender               0
region               0
education_level      0
employment_type      0
annual_income        0
loan_amount          0
loan_purpose         0
credit_score         0
repayment_history    0
transaction_count    0
spending_ratio       0
join_date            0
default_flag         0
dtype: int64

## 💡 Final Interpretation

✅ All missing values were handled using different imputation techniques, making the dataset ready for further preprocessing and Machine Learning.

---

# 📘 Part D: Outlier Handling

---

## 7.1 Z-Score Method

In [45]:
import numpy as np

# Select numerical columns
numeric_cols = ["age", "annual_income", "loan_amount", "credit_score"]

z_scores = np.abs(stats.zscore(df[numeric_cols]))
df_zscore = df[(z_scores < 3).all(axis=1)]

print("Original Shape:", df.shape)
print("After Z-Score:", df_zscore.shape)

Original Shape: (5000, 15)
After Z-Score: (5000, 15)

### 💡 Interpretation

✅ The IQR method detects observations outside the range Q1 − 1.5×IQR and Q3 + 1.5×IQR. These extreme values were removed to improve data quality.

## 7.2 IQR Method

In [46]:
df_iqr = df.copy()

for col in numeric_cols:

    Q1 = df_iqr[col].quantile(0.25)
    Q3 = df_iqr[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df_iqr[(df_iqr[col] < lower) | (df_iqr[col] > upper)]

    print(f"\nColumn: {col}")
    print("Outliers:", outliers.shape[0])

    df_iqr = df_iqr[(df_iqr[col] >= lower) & (df_iqr[col] <= upper)]

print("\nOriginal Shape:", df.shape)
print("After IQR:", df_iqr.shape)

Column: age
Outliers: 0

Column: annual_income
Outliers: 0

Column: loan_amount
Outliers: 0

Column: credit_score
Outliers: 0

Original Shape: (5000, 15)
After IQR: (5000, 15)

### 💡 Interpretation

✅ The Percentile method removes the lowest 1% and highest 1% of observations, reducing the influence of extreme values while preserving most of the data.

## 7.4 Winsorization Technique

In [47]:
df_winsor = df.copy()

for col in numeric_cols:
    df_winsor[col] = winsorize(df_winsor[col], limits=[0.01, 0.01])

print(df_winsor.head())

  customer_id   age  gender region education_level employment_type  \
0   CUST00001  54.0    Male  South        Graduate        Salaried
1   CUST00002  32.0    Male   East        Graduate   Self-Employed
2   CUST00003  25.0  Female   East        Graduate   Self-Employed
3   CUST00004  45.0    Male  South        Graduate   Self-Employed
4   CUST00005  51.0    Male  South        Graduate   Self-Employed

   annual_income  loan_amount loan_purpose  credit_score  repayment_history  \
0      886382.09    338184.20     Business         775.9                 12
1     2538050.29    274380.78     Business         484.9                  7
2     2550668.63   1631792.71    Education         316.0                  5
3     1286415.40    213936.12          Car         799.2                 17
4      997939.39     78230.40          Car         513.5                  5

   transaction_count  spending_ratio   join_date  default_flag
0                248           28.74  2023-09-09             0
1                439           62.15  2020-11-11             1
2                 63            6.80  2019-02-21             1
3                393            5.06  2023-08-08             0
4                370           34.34  2018-09-13             1

### 💡Interpretation

✅ Winsorization replaces extreme values with the 1st percentile and 99th percentile values instead of deleting them. This reduces the effect of outliers while keeping all records in the dataset.

# 📌 Final Conclusion

In [48]:
print("Original Dataset Shape :", df.shape)
print("After Z-Score :", df_zscore.shape)
print("After IQR :", df_iqr.shape)
print("After Winsorization :", df_winsor.shape)

Original Dataset Shape : (5000, 15)
After Z-Score : (5000, 15)
After IQR : (5000, 15)
After Winsorization : (5000, 15)

---

# 📘 PART E: Feature Engineering

---

## 8. Handle Variable Types

### 8.1 Mixed Variables (Numeric + Categorical)

In [49]:
# Check Datatypes

print(df.dtypes)

customer_id           object
age                  float64
gender                object
region                object
education_level       object
employment_type       object
annual_income        float64
loan_amount          float64
loan_purpose          object
credit_score         float64
repayment_history      int64
transaction_count      int64
spending_ratio       float64
join_date             object
default_flag           int64
dtype: object

In [50]:
numeric_cols = df.select_dtypes(include=['int64','float64']).columns

categorical_cols = df.select_dtypes(include=['object']).columns

print("Numeric Columns")
print(numeric_cols)

print("\nCategorical Columns")
print(categorical_cols)

Numeric Columns
Index(['age', 'annual_income', 'loan_amount', 'credit_score',
       'repayment_history', 'transaction_count', 'spending_ratio',
       'default_flag'],
      dtype='object')

Categorical Columns
Index(['customer_id', 'gender', 'region', 'education_level', 'employment_type',
       'loan_purpose', 'join_date'],
      dtype='object')

### 💡 Interpretation

✅ The dataset contains both numerical and categorical variables. Separating them helps apply appropriate preprocessing techniques.

## 8.2 Date & Time Variables

In [51]:
df["application_date"] = pd.date_range(
    start="2024-01-01",
    periods=len(df),
    freq="D"
)

df["Year"] = df["application_date"].dt.year
df["Month"] = df["application_date"].dt.month
df["Day"] = df["application_date"].dt.day
df["Weekday"] = df["application_date"].dt.day_name()

## 9. Encoding Categorical Variables

In [52]:
df.head

<bound method NDFrame.head of      customer_id   age  gender region education_level employment_type  \
0      CUST00001  54.0    Male  South        Graduate        Salaried
1      CUST00002  32.0    Male   East        Graduate   Self-Employed
2      CUST00003  25.0  Female   East        Graduate   Self-Employed
3      CUST00004  45.0    Male  South        Graduate   Self-Employed
4      CUST00005  51.0    Male  South        Graduate   Self-Employed
...          ...   ...     ...    ...             ...             ...
4995   CUST04996  53.0   Other   East         Primary        Salaried
4996   CUST04997  33.0  Female   West   Post-Graduate      Unemployed
4997   CUST04998  45.0   Other  North         Primary        Salaried
4998   CUST04999  43.0  Female  South         Primary      Unemployed
4999   CUST05000  59.0   Other  North   Post-Graduate        Salaried

      annual_income  loan_amount loan_purpose  credit_score  \
0         886382.09    338184.20     Business         775.9
1        2538050.29    274380.78     Business         484.9
2        2550668.63   1631792.71    Education         316.0
3        1286415.40    213936.12          Car         799.2
4         997939.39     78230.40          Car         513.5
...             ...          ...          ...           ...
4995     2724324.63    622050.50        Other         795.9
4996     2426825.86    513054.21        Other         778.4
4997     1354811.58   1028097.84        Other         426.5
4998     2670539.94    769693.77        Other         841.0
4999     2941024.87    627409.38    Education         530.3

      repayment_history  transaction_count  spending_ratio   join_date  \
0                    12                248           28.74  2023-09-09
1                     7                439           62.15  2020-11-11
2                     5                 63            6.80  2019-02-21
3                    17                393            5.06  2023-08-08
4                     5                370           34.34  2018-09-13
...                 ...                ...             ...         ...
4995                  4                396           57.59  2023-03-06
4996                 13                182           64.08  2024-01-14
4997                 16                410           45.97  2025-09-25
4998                  4                317           48.00  2020-05-14
4999                  9                388          112.00  2019-02-16

      default_flag application_date  Year  Month  Day    Weekday
0                0       2024-01-01  2024      1    1     Monday
1                1       2024-01-02  2024      1    2    Tuesday
2                1       2024-01-03  2024      1    3  Wednesday
3                0       2024-01-04  2024      1    4   Thursday
4                1       2024-01-05  2024      1    5     Friday
...            ...              ...   ...    ...  ...        ...
4995             1       2037-09-04  2037      9    4     Friday
4996             0       2037-09-05  2037      9    5   Saturday
4997             1       2037-09-06  2037      9    6     Sunday
4998             1       2037-09-07  2037      9    7     Monday
4999             1       2037-09-08  2037      9    8    Tuesday

[5000 rows x 20 columns]>

### 9.1 Ordinal Encoding (Education Level)

In [53]:
from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder()

df["education_level"] = encoder.fit_transform(df[["education_level"]])

df.head()

,customer_id,age,gender,region,education_level,employment_type,annual_income,loan_amount,loan_purpose,credit_score,repayment_history,transaction_count,spending_ratio,join_date,default_flag,application_date,Year,Month,Day,Weekday
0,CUST00001,54.0,Male,South,0.0,Salaried,886382.09,338184.20,Business,775.9,12,248,28.74,2023-09-09,0,2024-01-01,2024,1,1,Monday
1,CUST00002,32.0,Male,East,0.0,Self-Employed,2538050.29,274380.78,Business,484.9,7,439,62.15,2020-11-11,1,2024-01-02,2024,1,2,Tuesday
2,CUST00003,25.0,Female,East,0.0,Self-Employed,2550668.63,1631792.71,Education,316.0,5,63,6.80,2019-02-21,1,2024-01-03,2024,1,3,Wednesday
3,CUST00004,45.0,Male,South,0.0,Self-Employed,1286415.40,213936.12,Car,799.2,17,393,5.06,2023-08-08,0,2024-01-04,2024,1,4,Thursday
4,CUST00005,51.0,Male,South,0.0,Self-Employed,997939.39,78230.40,Car,513.5,5,370,34.34,2018-09-13,1,2024-01-05,2024,1,5,Friday

💡 Interpretation:

🔹 Ordinal Encoding converted the education_level categories into numerical values while preserving their natural order. This makes the categorical data suitable for machine learning algorithms.

### 9.2 Label Encoding (Binary Feature)

In [54]:
label = LabelEncoder()

df["gender"] = label.fit_transform(df["gender"])

df.head()

,customer_id,age,gender,region,education_level,employment_type,annual_income,loan_amount,loan_purpose,credit_score,repayment_history,transaction_count,spending_ratio,join_date,default_flag,application_date,Year,Month,Day,Weekday
0,CUST00001,54.0,1,South,0.0,Salaried,886382.09,338184.20,Business,775.9,12,248,28.74,2023-09-09,0,2024-01-01,2024,1,1,Monday
1,CUST00002,32.0,1,East,0.0,Self-Employed,2538050.29,274380.78,Business,484.9,7,439,62.15,2020-11-11,1,2024-01-02,2024,1,2,Tuesday
2,CUST00003,25.0,0,East,0.0,Self-Employed,2550668.63,1631792.71,Education,316.0,5,63,6.80,2019-02-21,1,2024-01-03,2024,1,3,Wednesday
3,CUST00004,45.0,1,South,0.0,Self-Employed,1286415.40,213936.12,Car,799.2,17,393,5.06,2023-08-08,0,2024-01-04,2024,1,4,Thursday
4,CUST00005,51.0,1,South,0.0,Self-Employed,997939.39,78230.40,Car,513.5,5,370,34.34,2018-09-13,1,2024-01-05,2024,1,5,Friday

### 💡 Interpretation

✅ Binary categorical values were converted into numerical values.

### 9.3 One-Hot Encoding

In [55]:
df = pd.get_dummies(
    df,
    columns=["region","loan_purpose"],
    drop_first=True
)

df.head()

,customer_id,age,gender,education_level,employment_type,annual_income,loan_amount,credit_score,repayment_history,transaction_count,...,Month,Day,Weekday,region_North,region_South,region_West,loan_purpose_Car,loan_purpose_Education,loan_purpose_Home,loan_purpose_Other
0,CUST00001,54.0,1,0.0,Salaried,886382.09,338184.20,775.9,12,248,...,1,1,Monday,False,True,False,False,False,False,False
1,CUST00002,32.0,1,0.0,Self-Employed,2538050.29,274380.78,484.9,7,439,...,1,2,Tuesday,False,False,False,False,False,False,False
2,CUST00003,25.0,0,0.0,Self-Employed,2550668.63,1631792.71,316.0,5,63,...,1,3,Wednesday,False,False,False,False,True,False,False
3,CUST00004,45.0,1,0.0,Self-Employed,1286415.40,213936.12,799.2,17,393,...,1,4,Thursday,False,True,False,True,False,False,False
4,CUST00005,51.0,1,0.0,Self-Employed,997939.39,78230.40,513.5,5,370,...,1,5,Friday,False,True,False,True,False,False,False

### 💡 Interpretation

✅ One-Hot Encoding converted categorical variables into multiple binary columns without introducing any order.

## 10.Encoding Numerical Features

### 10.1 Binning

In [56]:
df["income_group"] = pd.cut(
    df["annual_income"],
    bins=4,
    labels=[
        "Low",
        "Medium",
        "High",
        "Very High"
    ]
)

df[["annual_income","income_group"]].head()

   annual_income income_group
0      886382.09       Medium
1     2538050.29    Very High
2     2550668.63    Very High
3     1286415.40       Medium
4      997939.39       Medium

### 💡 Interpretation

✅ Annual income was divided into meaningful groups.

### 10.2 Binarization

In [57]:
binarizer = Binarizer(threshold=50000)

df["income_binary"] = binarizer.fit_transform(df[["annual_income"]])

df[["annual_income","income_binary"]].head()

   annual_income  income_binary
0      886382.09            1.0
1     2538050.29            1.0
2     2550668.63            1.0
3     1286415.40            1.0
4      997939.39            1.0

### 💡 Interpretation

✅ Income values greater than 50,000 were assigned 1, otherwise 0.

### 10.3 Quantile Binning

In [58]:
df["income_quantile"] = pd.qcut(
    df["annual_income"],
    q=4,
    labels=[
        "Q1",
        "Q2",
        "Q3",
        "Q4"
    ]
)

df[["annual_income","income_quantile"]].head()

   annual_income income_quantile
0      886382.09              Q2
1     2538050.29              Q4
2     2550668.63              Q4
3     1286415.40              Q2
4      997939.39              Q2

### 💡 Interpretation

✅ Income values were divided into four equal-frequency groups.

### 10.4 K-Means Binning

In [59]:
kmeans = KMeans(
    n_clusters=4,
    random_state=42,
    n_init=10
)

df["income_cluster"] = kmeans.fit_predict(
    df[["annual_income"]]
)

df[["annual_income","income_cluster"]].head()

   annual_income  income_cluster
0      886382.09               1
1     2538050.29               0
2     2550668.63               0
3     1286415.40               1
4      997939.39               1

### 💡 Interpretation

✅ K-Means grouped similar income values into four clusters based on similarity.

## 📌 Final Feature Engineering Summary

In [60]:
print(df.head())

print("\nFinal Shape :", df.shape)

  customer_id   age  gender  education_level employment_type  annual_income  \
0   CUST00001  54.0       1              0.0        Salaried      886382.09
1   CUST00002  32.0       1              0.0   Self-Employed     2538050.29
2   CUST00003  25.0       0              0.0   Self-Employed     2550668.63
3   CUST00004  45.0       1              0.0   Self-Employed     1286415.40
4   CUST00005  51.0       1              0.0   Self-Employed      997939.39

   loan_amount  credit_score  repayment_history  transaction_count  ...  \
0    338184.20         775.9                 12                248  ...
1    274380.78         484.9                  7                439  ...
2   1631792.71         316.0                  5                 63  ...
3    213936.12         799.2                 17                393  ...
4     78230.40         513.5                  5                370  ...

   region_South region_West  loan_purpose_Car loan_purpose_Education  \
0          True       False             False                  False
1         False       False             False                  False
2         False       False             False                   True
3          True       False              True                  False
4          True       False              True                  False

   loan_purpose_Home  loan_purpose_Other  income_group income_binary  \
0              False               False        Medium           1.0
1              False               False     Very High           1.0
2              False               False     Very High           1.0
3              False               False        Medium           1.0
4              False               False        Medium           1.0

   income_quantile  income_cluster
0               Q2               1
1               Q4               0
2               Q4               0
3               Q2               1
4               Q2               1

[5 rows x 29 columns]

Final Shape : (5000, 29)

### 💡 Final Interpretation

✅ Feature Engineering transformed the dataset into a machine learning-ready format by handling variable types, extracting date features, encoding categorical variables, and converting numerical variables into meaningful groups.

# 📊 PART F: Feature Scalling

### 11.Apply Multiple Scalling

### 11.1 Standardization (Z-Score Scaling)

In [61]:
scaler = StandardScaler()

df_standard = df.copy()

df_standard[["age", "annual_income", "loan_amount", "credit_score"]] = scaler.fit_transform(
    df_standard[["age", "annual_income", "loan_amount", "credit_score"]]
)

df_standard.head()

,customer_id,age,gender,education_level,employment_type,annual_income,loan_amount,credit_score,repayment_history,transaction_count,...,region_South,region_West,loan_purpose_Car,loan_purpose_Education,loan_purpose_Home,loan_purpose_Other,income_group,income_binary,income_quantile,income_cluster
0,CUST00001,0.667841,1,0.0,Salaried,-0.809608,-1.140357,1.269056,12,248,...,True,False,False,False,False,False,Medium,1.0,Q2,1
1,CUST00002,-0.764595,1,0.0,Self-Employed,1.155231,-1.250328,-0.574340,7,439,...,False,False,False,False,False,False,Very High,1.0,Q4,0
2,CUST00003,-1.220370,0,0.0,Self-Employed,1.170242,1.089293,-1.644269,5,63,...,False,False,False,True,False,False,Very High,1.0,Q4,0
3,CUST00004,0.081844,1,0.0,Self-Employed,-0.333725,-1.354510,1.416654,17,393,...,True,False,True,False,False,False,Medium,1.0,Q2,1
4,CUST00005,0.472508,1,0.0,Self-Employed,-0.676899,-1.588411,-0.393168,5,370,...,True,False,True,False,False,False,Medium,1.0,Q2,1

### 💡 Interpretation

💡 Standardization transformed the numerical features to have a mean of 0 and a standard deviation of 1, making them suitable for many machine learning algorithms.

### 11.2 Normalization

In [62]:
normalizer = Normalizer()

df_normalized = df.copy()

df_normalized[["age", "annual_income", "loan_amount", "credit_score"]] = normalizer.fit_transform(
    df_normalized[["age", "annual_income", "loan_amount", "credit_score"]]
)

df_normalized.head()

,customer_id,age,gender,education_level,employment_type,annual_income,loan_amount,credit_score,repayment_history,transaction_count,...,region_South,region_West,loan_purpose_Car,loan_purpose_Education,loan_purpose_Home,loan_purpose_Other,income_group,income_binary,income_quantile,income_cluster
0,CUST00001,0.000057,1,0.0,Salaried,0.934307,0.356469,0.000818,12,248,...,True,False,False,False,False,False,Medium,1.0,Q2,1
1,CUST00002,0.000013,1,0.0,Self-Employed,0.994207,0.107481,0.000190,7,439,...,False,False,False,False,False,False,Very High,1.0,Q4,0
2,CUST00003,0.000008,0,0.0,Self-Employed,0.842367,0.538905,0.000104,5,63,...,False,False,False,True,False,False,Very High,1.0,Q4,0
3,CUST00004,0.000035,1,0.0,Self-Employed,0.986452,0.164051,0.000613,17,393,...,True,False,True,False,False,False,Medium,1.0,Q2,1
4,CUST00005,0.000051,1,0.0,Self-Employed,0.996941,0.078152,0.000513,5,370,...,True,False,True,False,False,False,Medium,1.0,Q2,1

### 💡 Interpretation

Normalization scaled each record so that its magnitude became 1, helping algorithms that depend on vector length.

### 11.3 Min-Max Scaling

In [63]:
minmax = MinMaxScaler()

df_minmax = df.copy()

df_minmax[["age", "annual_income", "loan_amount", "credit_score"]] = minmax.fit_transform(
    df_minmax[["age", "annual_income", "loan_amount", "credit_score"]]
)

df_minmax.head()

,customer_id,age,gender,education_level,employment_type,annual_income,loan_amount,credit_score,repayment_history,transaction_count,...,region_South,region_West,loan_purpose_Car,loan_purpose_Education,loan_purpose_Home,loan_purpose_Other,income_group,income_binary,income_quantile,income_cluster
0,CUST00001,0.692308,1,0.0,Salaried,0.270822,0.166957,0.865587,12,248,...,True,False,False,False,False,False,Medium,1.0,Q2,1
1,CUST00002,0.269231,1,0.0,Self-Employed,0.840910,0.134959,0.336304,7,439,...,False,False,False,False,False,False,Very High,1.0,Q4,0
2,CUST00003,0.134615,0,0.0,Self-Employed,0.845265,0.815723,0.029101,5,63,...,False,False,False,True,False,False,Very High,1.0,Q4,0
3,CUST00004,0.519231,1,0.0,Self-Employed,0.408897,0.104645,0.907967,17,393,...,True,False,True,False,False,False,Medium,1.0,Q2,1
4,CUST00005,0.634615,1,0.0,Self-Employed,0.309327,0.036586,0.388323,5,370,...,True,False,True,False,False,False,Medium,1.0,Q2,1

### 💡 Interpretation

Min-Max Scaling transformed the numerical features into a range between 0 and 1 while preserving their relationships.

### 11.4 MaxAbs Scaling

In [64]:
from sklearn.preprocessing import MaxAbsScaler

maxabs_scaler = MaxAbsScaler()

df["annual_income_maxabs"] = maxabs_scaler.fit_transform(
    df[["annual_income"]]
)

df[["annual_income", "annual_income_maxabs"]].head()

   annual_income  annual_income_maxabs
0      886382.09              0.295562
1     2538050.29              0.846308
2     2550668.63              0.850515
3     1286415.40              0.428953
4      997939.39              0.332761

### 💡 Interpretation

📌 MaxAbs Scaling scales values between -1 and 1 without changing the sign of the data.

### 11.5 Robust Scaling

In [65]:
from sklearn.preprocessing import RobustScaler

robust_scaler = RobustScaler()

df["loan_amount_robust"] = robust_scaler.fit_transform(
    df[["loan_amount"]]
)

### 💡 Interpretation

📌 Robust Scaling reduces the effect of outliers by using the median and quartiles.

# 📊 Part G: Feature Construction & Transformation

## 12. Apply Transformations

### 12.1 Function Transformer — Log Transform

In [66]:
from sklearn.preprocessing import FunctionTransformer

log_transformer = FunctionTransformer(np.log1p)

df["annual_income_log"] = log_transformer.fit_transform(
    df[["annual_income"]]
)

### 💡 Interpretation

 Log transformation reduces skewness and makes the income data more balanced.

### 12.2 Function Transformer — Reciprocal Transform

In [67]:
reciprocal_transformer = FunctionTransformer(
    lambda x: 1 / (x + 1)
)

df["spending_ratio_reciprocal"] = reciprocal_transformer.fit_transform(
    df[["spending_ratio"]]
)

### 💡 Interpretation

 Reciprocal transformation helps reduce the effect of high values.

### 12.3 Function Transformer — Square Root

In [68]:
sqrt_transformer = FunctionTransformer(np.sqrt)

df["loan_amount_sqrt"] = sqrt_transformer.fit_transform(
    df[["loan_amount"]]
)

### 💡 Interpretation

 Square root transformation reduces the skewness of loan amount.

### 12.4 Power Transformer — Box-Cox

In [69]:
from sklearn.preprocessing import PowerTransformer

boxcox = PowerTransformer(method="box-cox")

df["annual_income_boxcox"] = boxcox.fit_transform(
    df[["annual_income"]]
)

### 💡 Interpretation

 Yeo-Johnson transformation reduces skewness and improves the distribution of loan amount.

### 12.6 Column Transformer

In [81]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), ["gender"])
    ],
    remainder="passthrough"
)

X = preprocessor.fit_transform(df)

X

array([[0.0, 1.0, 0.0, ..., 0.38153320539227054, 41.333333333333336,
        28.74],
       [0.0, 1.0, 0.0, ..., 0.10810691225507593, 73.16666666666667,
        62.15],
       [1.0, 0.0, 0.0, ..., 0.6397509620840085, 10.5, 6.8],
       ...,
       [0.0, 0.0, 1.0, ..., 0.7588493154155059, 68.33333333333333, 45.97],
       [1.0, 0.0, 0.0, ..., 0.2882165357167435, 52.833333333333336, 48.0],
       [0.0, 0.0, 1.0, ..., 0.21333018513372856, 64.66666666666667,
        112.0]], shape=(5000, 40), dtype=object)

### 💡 Interpretation

 Column Transformer applies different preprocessing methods to numerical and categorical columns in one pipeline.

## 13. Construct New Features

### 13.1 Debt-to-Income Ratio

In [71]:
df["debt_to_income_ratio"] = (
    df["loan_amount"] / df["annual_income"]
)

### 💡 Interpretation

 Debt-to-Income Ratio shows the loan amount compared with the customer's income.

### 13.2 Average Monthly Transactions

In [72]:
df["avg_monthly_transactions"] = (
    df["transaction_count"] / 6
)

### 💡 Interpretation

 Average monthly transactions show the customer's average transaction activity per month.

### 13.3 Spending-to-Income Ratio

In [73]:
df["spending_to_income_ratio"] = (
    df["spending_ratio"]
)

### 💡 Interpretation

 Spending-to-Income Ratio shows how much the customer spends compared with their income.

# ✅ Final Check

In [74]:
df.head()

,customer_id,age,gender,education_level,employment_type,annual_income,loan_amount,credit_score,repayment_history,transaction_count,...,income_cluster,annual_income_maxabs,loan_amount_robust,annual_income_log,spending_ratio_reciprocal,loan_amount_sqrt,annual_income_boxcox,debt_to_income_ratio,avg_monthly_transactions,spending_to_income_ratio
0,CUST00001,54.0,1,0.0,Salaried,886382.09,338184.20,775.9,12,248,...,1,0.295562,-0.654835,13.694905,0.033625,581.536069,-0.751077,0.381533,41.333333,28.74
1,CUST00002,32.0,1,0.0,Self-Employed,2538050.29,274380.78,484.9,7,439,...,0,0.846308,-0.717802,14.746907,0.015835,523.813688,1.114696,0.108107,73.166667,62.15
2,CUST00003,25.0,0,0.0,Self-Employed,2550668.63,1631792.71,316.0,5,63,...,0,0.850515,0.621804,14.751866,0.128205,1277.416420,1.127424,0.639751,10.500000,6.80
3,CUST00004,45.0,1,0.0,Self-Employed,1286415.40,213936.12,799.2,17,393,...,1,0.428953,-0.777454,14.067371,0.165017,462.532291,-0.250065,0.166304,65.500000,5.06
4,CUST00005,51.0,1,0.0,Self-Employed,997939.39,78230.40,513.5,5,370,...,1,0.332761,-0.911379,13.813449,0.028297,279.696979,-0.606483,0.078392,61.666667,34.34

In [75]:
df.shape

(5000, 38)

# 📊 Part H: Final Deliverable

## 14. Final Cleaned & Transformed Dataset

In [76]:
# Check final dataset
print("Final Shape:", df.shape)
df.head()

Final Shape: (5000, 38)

,customer_id,age,gender,education_level,employment_type,annual_income,loan_amount,credit_score,repayment_history,transaction_count,...,income_cluster,annual_income_maxabs,loan_amount_robust,annual_income_log,spending_ratio_reciprocal,loan_amount_sqrt,annual_income_boxcox,debt_to_income_ratio,avg_monthly_transactions,spending_to_income_ratio
0,CUST00001,54.0,1,0.0,Salaried,886382.09,338184.20,775.9,12,248,...,1,0.295562,-0.654835,13.694905,0.033625,581.536069,-0.751077,0.381533,41.333333,28.74
1,CUST00002,32.0,1,0.0,Self-Employed,2538050.29,274380.78,484.9,7,439,...,0,0.846308,-0.717802,14.746907,0.015835,523.813688,1.114696,0.108107,73.166667,62.15
2,CUST00003,25.0,0,0.0,Self-Employed,2550668.63,1631792.71,316.0,5,63,...,0,0.850515,0.621804,14.751866,0.128205,1277.416420,1.127424,0.639751,10.500000,6.80
3,CUST00004,45.0,1,0.0,Self-Employed,1286415.40,213936.12,799.2,17,393,...,1,0.428953,-0.777454,14.067371,0.165017,462.532291,-0.250065,0.166304,65.500000,5.06
4,CUST00005,51.0,1,0.0,Self-Employed,997939.39,78230.40,513.5,5,370,...,1,0.332761,-0.911379,13.813449,0.028297,279.696979,-0.606483,0.078392,61.666667,34.34

In [77]:
df.to_csv("Final_Cleaned_Customer_Credit_Risk.csv", index=False)

print("Final dataset saved successfully!")

Final dataset saved successfully!

## 15. Final Report

# 📊 Final Data Preprocessing Report

## 🧹 Missing Value Handling

Missing values were handled using different methods such as mean/median imputation for numerical columns and most frequent category imputation for categorical columns.

## 🚨 Outlier Handling

Outliers were detected using methods such as Z-score and IQR. Suitable techniques were applied to numerical features to reduce the effect of extreme values.

## 🔤 Encoding

Categorical variables were converted into numerical form using:
- Label Encoding
- One-Hot Encoding
- Ordinal Encoding

This makes categorical data suitable for Machine Learning models.

## 📏 Scaling

Different scaling methods were applied, including:
- Standardization
- Normalization
- Min-Max Scaling
- MaxAbs Scaling
- Robust Scaling

Scaling helps bring numerical features to a comparable range.

## 🔄 Transformations

Transformations such as Log, Reciprocal, Square Root, Box-Cox and Yeo-Johnson were applied to reduce skewness and improve data distribution.

## 🆕 Feature Engineering

New features were created, including:
- Debt-to-Income Ratio
- Average Monthly Transactions
- Spending-to-Income Ratio

These features provide additional information about customer financial behavior.

## 📐 Final Dataset Shape

The final dataset contains the cleaned and transformed customer credit risk data.

## 🎯 Conclusion

The dataset was successfully cleaned, transformed and prepared for Machine Learning. Missing values, outliers, categorical variables and numerical features were handled using suitable preprocessing techniques. The final dataset is now more suitable for analysis and ML modeling.

In [82]:
print("Final Shape:", df.shape)
print("Missing Values:")
print(df.isnull().sum())

Final Shape: (5000, 38)
Missing Values:
customer_id                  0
age                          0
gender                       0
education_level              0
employment_type              0
annual_income                0
loan_amount                  0
credit_score                 0
repayment_history            0
transaction_count            0
spending_ratio               0
join_date                    0
default_flag                 0
application_date             0
Year                         0
Month                        0
Day                          0
Weekday                      0
region_North                 0
region_South                 0
region_West                  0
loan_purpose_Car             0
loan_purpose_Education       0
loan_purpose_Home            0
loan_purpose_Other           0
income_group                 0
income_binary                0
income_quantile              0
income_cluster               0
annual_income_maxabs         0
loan_amount_robust           0
annual_income_log            0
spending_ratio_reciprocal    0
loan_amount_sqrt             0
annual_income_boxcox         0
debt_to_income_ratio         0
avg_monthly_transactions     0
spending_to_income_ratio     0
dtype: int64